name: flutter_to_do_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  app_settings: ^5.1.1
  date_picker_timeline: ^1.2.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^18.0.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.11
  flutter_timezone: ^3.0.1
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  sqflite: ^2.4.0
  timezone: ^0.10.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
